#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE 
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status "${app}_api" >/dev/null
then
	ynh_script_progression --message="Removing ${app}_api service integration..."
	yunohost service remove "${app}_api"
fi

if ynh_exec_warn_less yunohost service status "${app}_front" >/dev/null
then
	ynh_script_progression --message="Removing ${app}_front service integration..."
	yunohost service remove "${app}_front"
fi

ynh_remove_systemd_config --service="${app}_api"
ynh_remove_systemd_config --service="${app}_front"

# Remove a database if it exists, along with the associated user
ynh_mongo_remove_db --db_user=$db_user --db_name=$db_name
ynh_remove_mongo

ynh_remove_nginx_config

ynh_remove_logrotate

#ynh_remove_fail2ban_config

# Remove other various files specific to the app... such as :

ynh_secure_remove --file="/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
